### ISSUE TITLE
Is there any usage tutorial?

### ISSUE THREAD

**Issue by Jackeyasdzz** [ThatBatLuna/Beadi#19]
Are there any usage tutorials and the functions of each module?

**Comment by ThatBatLuna** [comment]
Yeahhh.... that's on my list for stuff I wanna do for the next release, however then life kinda got in the way and I didn't have much time to do that yet ^^

I guess your best bet with the currently released versions is to just plug all of the outputs of a node into a `Display` node and then just twiddle with the knobs a bit and experiment around.

Also if you go to the second tab ("File") of the right sidebar and discard your current file, there should be a "Hello" message, that allows you to open some examples.

Assuming you are using the Beta Version, a quick summary:

* Display: Displays whatever values get put into them on your screen
* Buttplug: If you connect to an Intiface-Central server in the uppermost tab of the right sidebar you can select and control toys
* Sensor: Same as the above, but for sensors instead of toys

* Value: Constant value
* Wave Generator: Generates a sine wave
* Random Generator: Generates a new random value every so often
* Random Timer: Generates alternating 1 or 0 in the "Value" output, holding the value for a given time. The "Progress" output generates a value from 0 to 1 representing the progress until the next switch of the "value" output. The higher the value of the "Dev" inputs (short for deviation) is, the more randomized the respective times are.

* Add, Subtract, Divide and Multiply do exactly what they say
* Mix "Blends" between two values depending on the amount (If the amount is zero, the output is exactly what comes in in "Value 0", if the amount is one, the output is exactly what comes in in "Value 1". if the amount is in between it takes a weighted average between the two values. 
* Clamp, Ensures the Values is between a minimum and a maximum
* Curve: Allows you to draw your own curve in the black area, the output value is the curve, sampled at the x coordinate specified by the input value. (useful if you plug the "progress" output of a random timer node into the input of the curve node, and then you can more or less draw your own patterns).
* Hysteresis: Think of it like a light switch, whenever the "Value" is higher than "High Threshold" it flicks it on, and it stays on until the "Value" gets lower than the "Low Threshold", where it flicks it off, and then it stays off until the "Value" is once again higher than the high threshold, etc.
* Memory: When it receives a signal in the "Save" input (e.g from a "Button" node), it saves the current value that comes in to the "Value" input and holds that until the next signal gets into the "Save" input. (you could for example plug a random generator into the "Value" and a button into the "Save" etc..)
* Button: Allows you to send signals and view it from the mobile interface (third tab on the right sidebar)
* Slider: Basically the same as "Value", but it's display in the mobile interface
* Toggle: Outputs either the "Off" input or the "On" input, and allows you to toggle between them
* Delay: Similar to a random timer node. When it receives a signal in the "Signal" input, the "Progress" will slowly increase from 0 to 1, while its running the "Running" output will be 1 and when it's done the "Signal" output will fire. (E.g connect the progress to a curve node, and the "Signal" input to a button, and you got yourself a button that plays a little pattern)
* On Raising Edge: Whenever the "Value" goes from below a one to above a one, the signal fires

* Comment: Just a field of text that can be used to do comments in your graph... However it seems that that's currently broken in the beta version
* E621: Enter a search query for e621.net and everytime it receives a signal it will fetch an image for that query. This is also displayed in the mobile view.

**Comment by Jackeyasdzz** [comment]
What can I do to achieve random pause times so that the toy will not vibrate during the pause time, in the curves example. I tried setting all other timers to 0. Only off time has a value, but the toy still vibrates.

**Comment by Jackeyasdzz** [comment]
What can I do to achieve random pause times so that the toy will not vibrate during the pause time, in the curves example. I tried setting all other timers to 0. Only off time has a value, but the toy still vibrates.

**Comment by ThatBatLuna** [comment]
You could try to connect the "Value" output of a "Random Timer" to your toy and then raise the on or off time deviations (The "... - Dev" Values)

**Comment by Jackeyasdzz** [comment]
can you delete this issuse
