### ISSUE TITLE
problem with npm searching for a package.json inside of changelog.md when installing changelog dependency

### ISSUE THREAD

**Issue by johnlong21** [ThatBatLuna/Beadi#7]
i was attempting to install and build a local version of beadi(i prefer to have things on my own system over using a browser), when trying to use npm install gave me this error:

```
npm ERR! code ENOTDIR
npm ERR! syscall open
npm ERR! path /home/johnlong/git-projects/Beadi/CHANGELOG.md/package.json
npm ERR! errno -20
npm ERR! ENOTDIR: not a directory, open '/home/johnlong/git-projects/Beadi/CHANGELOG.md/package.json'
```

thinking it might be because of my node version i switched to the latest version "19.4" but that did not work so i do not know what needs to be done to fix this.

node version:18.2.0
npm version:9.3.1

**Comment by ThatBatLuna** [comment]
Interesting, I knew this was a kinda weird thing I did, to display the current Changelog in the WelcomeNode.

I believe to temporarily fix this you can just remove the line 30 from the package.json `"CHANGELOG": "file:./CHANGELOG.md"` while doing the install, and re-add it later.

I am doing this weird thing, so that I can do this https://github.com/ThatBatLuna/Beadi/blob/2835e4fdce69ee77728e494b6d6aced02befc7c2/src/nodes/WelcomeNode.tsx#L6

I'll look into this^^

**Comment by ThatBatLuna** [comment]
Okay I can reproduce this with the versions you specified

**Comment by ThatBatLuna** [comment]
This should be fixed by c4f93216248fa04310700a8e3afdb12c7a903aa8 on the hotfix branch. If you could try it out and verify it works now I'd be very glad.

**Comment by johnlong21** [comment]
just confirmed and yes that commit seems to have fixed the problem

**Comment by ThatBatLuna** [comment]
Perfect, then I'll merge it to main!

Thank you a lot!
